GET http://localhost:3000/blogs

###


GET http://localhost:3000/blogs/300

###
POST http://localhost:3000/blogs
Content-Type: application/json

{
    "blog_id": 670,
    "title": "Blog 670",
    "blog_content": "about my new blog670",
    "author": "Test Author Blogger670",
    "created": "2025-06-17"
}

###
DELETE http://localhost:3000/blogs/660

###
PATCH  http://localhost:3000/blogs/600
Content-Type: application/json

{
    "blog_content": "Blog 600 Updated"
}

###
GET http://localhost:3000/users

###


GET http://localhost:3000/users/1

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "user_id": 3,
    "username": "testuser3",
    "email": "testuser3@test.com",
    "user_password": "Test3",
    "created": "2025-04-08",
    "blog_id": 810
}

###
DELETE http://localhost:3000/users/5

###
PATCH  http://localhost:3000/users/5
Content-Type: application/json

{
    "email": "email updated"
}