GET http://localhost:3000/blogs

###

GET http://localhost:3000/blogs/67e5b5def1c9eb3852d02b99

###
POST http://localhost:3000/blogs
Content-Type: application/json

{
    "title": "Blog 4",
    "content": "about my new blog4",
    "author": "Test Author Blogger4"
}

###
DELETE http://localhost:3000/blogs/67e6aa395a84b5e468bccaa4

###
PATCH http://localhost:3000/blogs/67e5b5def1c9eb3852d02b99
Content-Type: application/json

{
    "title": "Blog Updated"
}

###

GET http://localhost:3000/users

###

GET http://localhost:3000/users/67e6bf163d6b656a9262e1d0

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "TesterThree",
    "email": "testthree@gmail.com",
    "password": "test1234"
}

###
DELETE http://localhost:3000/users/67e6bf163d6b656a9262e1d0

###
PATCH http://localhost:3000/users/67e6bf203d6b656a9262e1d2
Content-Type: application/json

{
    "email": "emailupdated@test.com"
}