GET http://localhost:3000/creatures

###

GET http://localhost:3000/creatures/67e5910e35ff674dd5ba26a3

###
POST http://localhost:3000/creatures
Content-Type: application/json

{
    "name": "Drago",
    "creatureType": "Dragon",
    "creatureSkill": "fire-breathing",
    "weakness": "underbelly"
}

###
DELETE http://localhost:3000/creatures/67e5910e35ff674dd5ba26a3

###
PATCH http://localhost:3000/creatures/67e59f9387e3db4c83b90824
Content-Type: application/json

{
    "name": "Drago Updated again"
}

###
POST http://localhost:3000/creatures
Content-Type: application/json

{
    "name": "SeaConda",
    "creatureType": "Sea-Monster",
    "creatureSkill": "sharp-biting",
    "weakness": "electricity"
}

###
POST http://localhost:3000/randomCreature
Content-Type: application/json

{
   



}

###
POST http://localhost:3000/creatures
Content-Type: application/json

{
    "name": "Booby",
    "creatureType": "Ghost",
    "creatureSkill": "turn invisible",
    "weakness": "cross"
}